// nano-codeblock/packages/solid/src/CodeBlock.tsx
import { For, Component, createMemo, createSignal, onMount } from 'solid-js';
import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';

export interface CodeBlockProps {
  code: string;
  lang: string;
  theme?: Theme;
}

export const CodeBlock: Component<CodeBlockProps> = (props) => {
  const lines = createMemo<Token[][]>(() => highlight(props.code, props.lang));
  const [fadeIn, setFadeIn] = createSignal(false);

  onMount(() => setFadeIn(true));

  const handleCopy = () => {
    void copyToClipboard(props.code);
  };

  return (
    <pre class={`cb ${props.theme ?? Theme.dracula}`}>
      <button type="button" onClick={handleCopy} aria-label="Copy code" class="cb-copy">
        Copy
      </button>
      <code classList={{ 'cb-fade-in': fadeIn() }}>
        <For each={lines()}>
          {(line, i) => (
            <span class="cb-line">
              <For each={line}>
                {(token) => <span class={`cb-${token.type}`}>{token.content}</span>}
              </For>
              {i() < lines().length - 1 && '\n'}
            </span>
          )}
        </For>
      </code>
    </pre>
  );
};

// nano-codeblock/packages/svelte/src/CodeBlock.svelte
<script lang="ts">
  import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';
  import { onMount } from 'svelte';

  export let code: string;
  export let lang: string;
  export let theme: Theme = Theme.dracula;

  let lines: Token[][] = [];
  $: lines = highlight(code, lang);
  let fade = false;

  onMount(() => {
    fade = true;
  });

  function handleCopy() {
    void copyToClipboard(code);
  }
</script>

<pre class={`cb ${theme}`}> 
  <button type="button" class="cb-copy" on:click={handleCopy} aria-label="Copy code">Copy</button>
  <code class:cb-fade-in={fade}>
    {#each lines as line, i}
      <span class="cb-line">
        {#each line as token}
          <span class={`cb-${token.type}`}>{token.content}</span>
        {/each}{#if i < lines.length - 1}
        \n{/if}
      </span>
    {/each}
  </code>
</pre>
