// nano-codeblock/packages/vue/src/CodeBlock.vue
<template>
  <pre :class="`cb ${appliedTheme}`">
    <button type="button" class="cb-copy" @click="handleCopy" aria-label="Copy code">Copy</button>
    <code>
      <span v-for="(line, i) in lines" :key="i" class="cb-line">
        <span v-for="(token, j) in line" :key="j" :class="`cb-${token.type}`">{{ token.content }}</span><template v-if="i < lines.length - 1">\n</template>
      </span>
    </code>
  </pre>
</template>

<script setup lang="ts">
import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';
import { computed } from 'vue';

const props = defineProps<{ code: string; lang: string; theme?: Theme }>();

const lines = computed<Token[][]>(() => highlight(props.code, props.lang));
const appliedTheme = computed(() => props.theme ?? Theme.dracula);

function handleCopy() {
  void copyToClipboard(props.code);
}
</script>

// nano-codeblock/packages/react/src/CodeBlock.tsx
import React from 'react';
import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';

export interface CodeBlockProps {
  code: string;
  lang: string;
  theme?: Theme;
}

export function CodeBlock({ code, lang, theme = Theme.dracula }: CodeBlockProps) {
  const lines = React.useMemo<Token[][]>(() => highlight(code, lang), [code, lang]);

  const handleCopy = React.useCallback(() => {
    void copyToClipboard(code);
  }, [code]);

  return (
    <pre className={`cb ${theme}`}>
      <button type="button" onClick={handleCopy} aria-label="Copy code" className="cb-copy">
        Copy
      </button>
      <code>
        {lines.map((line, i) => (
          <span key={i} className="cb-line">
            {line.map((token, j) => (
              <span key={j} className={`cb-${token.type}`}>
                {token.content}
              </span>
            ))}
            {i < lines.length - 1 && '\n'}
          </span>
        ))}
      </code>
    </pre>
  );
}
