// nano-codeblock/packages/svelte/src/CodeBlock.svelte
<script lang="ts">
  import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';

  export let code: string;
  export let lang: string;
  export let theme: Theme = Theme.dracula;

  let lines: Token[][] = [];
  $: lines = highlight(code, lang);

  function handleCopy() {
    void copyToClipboard(code);
  }
</script>

<pre class={`cb ${theme}`}> 
  <button type="button" class="cb-copy" on:click={handleCopy} aria-label="Copy code">Copy</button>
  <code>
    {#each lines as line, i}
      <span class="cb-line">
        {#each line as token}
          <span class={`cb-${token.type}`}>{token.content}</span>
        {/each}{#if i < lines.length - 1}
        \n{/if}
      </span>
    {/each}
  </code>
</pre>

// nano-codeblock/packages/vue/src/CodeBlock.vue
<template>
  <pre :class="`cb ${appliedTheme}`">
    <button type="button" class="cb-copy" @click="handleCopy" aria-label="Copy code">Copy</button>
    <code>
      <span v-for="(line, i) in lines" :key="i" class="cb-line">
        <span v-for="(token, j) in line" :key="j" :class="`cb-${token.type}`">{{ token.content }}</span><template v-if="i < lines.length - 1">\n</template>
      </span>
    </code>
  </pre>
</template>

<script setup lang="ts">
import { highlight, Theme, copyToClipboard, Token } from '@nano-codeblock/core';
import { computed } from 'vue';

const props = defineProps<{ code: string; lang: string; theme?: Theme }>();

const lines = computed<Token[][]>(() => highlight(props.code, props.lang));
const appliedTheme = computed(() => props.theme ?? Theme.dracula);

function handleCopy() {
  void copyToClipboard(props.code);
}
</script>
